---
# Install Docker main tasks on Supported system
- name: Install Docker main tasks on Supported system
  block:

   # Include Initialize tasks (Linux)
   - name: Include Initialize tasks
     include_tasks: "initialize.yml"

   # Include Install tasks (Linux)
   - name: Include Install tasks for ({{ ansible_distribution }})
     include_tasks: "install-{{ ansible_distribution }}.yml"

   # Flush Handlers
   - name: Force all notified handlers to run
     meta: flush_handlers

   # Include Install Compose tasks (Linux)
   - name: Include Install Compose tasks for ({{ ansible_distribution }})
     include_tasks: "install-Compose.yml"

   # Include Install Swarm tasks (Linux)
   - name: Include Install Swarm tasks for ({{ ansible_distribution }})
     include_tasks: "install-Swarm.yml"
     when:
      - docker_swarm_enabled | bool

   # Include Post Install tasks (Linux)
   - name: Include Post Install tasks for ({{ ansible_distribution }})
     include_tasks: "post-Install.yml"
     when:
      - docker_customization_script_source_path | length > 0

  when:
   - ansible_os_family == "RedHat" or ansible_os_family == "Debian"
