---
# Install Docker main tasks on Supported system
- name: Install Docker main tasks on Supported system
  block:

   # Include Initialize tasks (Linux)
   - name: Include Initialize tasks
     include_tasks: "initialize.yml"

   # Include Install tasks (Linux)
   - name: Include Install tasks for ({{ ansible_distribution }})
     include_tasks: "install-{{ ansible_distribution }}.yml"

   # Include Install Compose tasks (Linux)
   - name: Include Install Compose tasks for ({{ ansible_distribution }})
     include_tasks: "install-compose.yml"

  when:
   - ansible_os_family == "RedHat" or ansible_os_family == "Debian" or ansible_os_family == "Suse"
