---

# Docker version
docker_version: "5:19.03.1~3-0~ubuntu-xenial"

# Install docker community
docker_install_community: true

# System architecture
docker_os_architecture: "{{ ansible_architecture | replace('amd64', 'x86_64') }}"

# Docker authorized users
docker_authorized_users:
 - jetune
 - hmefoo
 - ltchatchouang

# Install compose
docker_install_compose: true

# Docker compose version
docker_compose_version: "1.24.1"

# Docker compose URL
docker_compose_url: "{{ 'https://github.com/docker/compose/releases/download/'\
+ docker_compose_version + '/docker-compose-' + ansible_system + '-' + docker_os_architecture }}"

# Docker compose checksum
docker_compose_checksum: "sha256:cfb3439956216b1248308141f7193776fcf4b9c9b49cbbe2fb07885678e2bb8a"

# Docker datas
docker_data_dir: "/kis/docker/datas"

# Docker Host adress
docker_host: "fd://"

# Extras Options
docker_extras_options:
 - "--log-level debug"
 - "--label TEST=true"
 - "--icc"
 - "--registry-mirror https://images.lab.kube-cloud.be"

# Docker role post script (for some initialization like plugin install & configuration)
docker_customization_script_source_path: "scripts/post-install.sh"

# Docker post script parameters
docker_customization_script_parameters:
 - "param1"
 - "param2"
 - "param3"
 - "param4"

# Path to store customization script
docker_customization_script_dest_path: "/tmp/customization.sh"

# Is docker swarm enabled ?
docker_swarm_enabled: false

# Is host docker swarm master ?
docker_swarm_master: false

# Docker swarm master join token
docker_swarm_master_join_token: ""

# Docker swarm master advertise IP
docker_swarm_advertise_ip: "127.0.0.1"

# Docker swarm master advertise port
docker_swarm_advertise_port: 2377

# Docker swarm master listen IP
docker_swarm_listen_ip: "0.0.0.0"

# Docker swarm worker join token
docker_swarm_worker_join_token: ""

# Docker swarm extra options
docker_swarm_extras_options:
 - "--availability active"
 - "--task-history-limit 5"
 - "--force-new-cluster"
 - "--dispatcher-heartbeat 10s"
 - "--default-addr-pool 10.20.0.0/16"
 - "--default-addr-pool-mask-length 16"
 - "--autolock"
 - "--data-path-addr 127.0.0.1"
 - "--data-path-port 4789"
 - "--cert-expiry 2160h0m0s"
